version: "3"

services:
  valiantos:
    container_name: valiantos
    build:
      context: .
      dockerfile: Dockerfile.solo
    restart: always
    ports:
      - 3001:3000
    networks:
      - dokploy-network
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.valiantos.rule=Host(`valiantos.valiantlynx.com`)
      - traefik.http.routers.valiantos.entrypoints=web
      - traefik.http.services.valiantos.loadbalancer.server.port=3000

